"""Skill catalog and synonym map for the job description extractor."""

SKILLS_LIST = [
    "Python",
    "Java",
    "JavaScript",
    "TypeScript",
    "C++",
    "C#",
    "R",
    "SQL",
    "PHP",
    "Go",
    "Ruby",
    "Scala",
    "Swift",
    "Kotlin",
    "Bash",
    "Django",
    "Flask",
    "FastAPI",
    "React",
    "Angular",
    "Vue.js",
    "Node.js",
    "Express.js",
    "Spring Boot",
    "ASP.NET",
    "Machine Learning",
    "Deep Learning",
    "Artificial Intelligence",
    "Natural Language Processing",
    "Computer Vision",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "Pandas",
    "NumPy",
    "Matplotlib",
    "Seaborn",
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "SQLite",
    "Redis",
    "Oracle",
    "AWS",
    "Azure",
    "GCP",
    "Docker",
    "Kubernetes",
    "Git",
    "GitHub",
    "Linux",
    "CI/CD",
    "Jenkins",
    "REST API",
    "GraphQL",
    "Agile",
    "Scrum",
    "Tableau",
    "Power BI",
    "Selenium",
]

SYNONYMS = {
    "ml": "Machine Learning",
    "ai": "Artificial Intelligence",
    "nlp": "Natural Language Processing",
    "js": "JavaScript",
    "k8s": "Kubernetes",
    "tf": "TensorFlow",
    "dl": "Deep Learning",
    "cv": "Computer Vision",
    "node": "Node.js",
}
